# Generated by Django 3.2.7 on 2021-09-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Branch',
            new_name='Address',
        ),
    ]
