# Generated by Django 3.2.7 on 2021-09-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakerapp', '0003_auto_20210919_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Contact_no',
            field=models.IntegerField(),
        ),
    ]
