# Generated by Django 3.2.7 on 2021-09-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fakerapp', '0005_auto_20210919_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Contact_no',
        ),
    ]
